In [1]:
import pandas as pd

df = pd.read_csv("../data/recruitment_pipeline_biased.csv")
df.head()

,CandidateID,Gender,Ethnicity,DisabilityStatus,RoleType,StageReached
0,1,Female,Other,NaN,Mid-Level,Screened
1,2,Prefer Not to Say,Mixed,Sensory,Mid-Level,Applied
2,3,Non-Binary,Hispanic/Latinx,NaN,Senior,Screened
3,4,Male,Other,Mental Health,Senior,Applied
4,5,Male,Hispanic/Latinx,Mental Health,Mid-Level,Hired

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CandidateID       500 non-null    int64
 1   Gender            500 non-null    str
 2   Ethnicity         500 non-null    str
 3   DisabilityStatus  103 non-null    str
 4   RoleType          500 non-null    str
 5   StageReached      500 non-null    str
dtypes: int64(1), str(5)
memory usage: 23.6 KB

In [3]:
df.describe(include='all')

        CandidateID  Gender Ethnicity DisabilityStatus   RoleType StageReached
count    500.000000     500       500              103        500          500
unique          NaN       4         6                5          3            5
top             NaN  Female     Black         Physical  Mid-Level      Applied
freq            NaN     140        95               31        172          207
mean     250.500000     NaN       NaN              NaN        NaN          NaN
std      144.481833     NaN       NaN              NaN        NaN          NaN
min        1.000000     NaN       NaN              NaN        NaN          NaN
25%      125.750000     NaN       NaN              NaN        NaN          NaN
50%      250.500000     NaN       NaN              NaN        NaN          NaN
75%      375.250000     NaN       NaN              NaN        NaN          NaN
max      500.000000     NaN       NaN              NaN        NaN          NaN

In [5]:
df.columns

Index(['CandidateID', 'Gender', 'Ethnicity', 'DisabilityStatus', 'RoleType',
       'StageReached'],
      dtype='str')

In [6]:
df['StageReached'].value_counts()

StageReached
Applied        207
Screened       172
Interviewed     61
Shortlisted     46
Hired           14
Name: count, dtype: int64

In [7]:
stage_counts = df['StageReached'].value_counts().reindex([
    'Applied', 'Screened', 'Interviewed', 'Shortlisted', 'Hired'
])

dropoff = stage_counts.pct_change().abs() * 100

dropoff

StageReached
Applied              NaN
Screened       16.908213
Interviewed    64.534884
Shortlisted    24.590164
Hired          69.565217
Name: count, dtype: float64

In [8]:
conversion = stage_counts / stage_counts.shift(1) * 100
conversion

StageReached
Applied              NaN
Screened       83.091787
Interviewed    35.465116
Shortlisted    75.409836
Hired          30.434783
Name: count, dtype: float64

In [9]:
df.columns

Index(['CandidateID', 'Gender', 'Ethnicity', 'DisabilityStatus', 'RoleType',
       'StageReached'],
      dtype='str')

In [10]:
gender_selection = df.groupby('Gender')['StageReached'].apply(lambda x: (x == 'Hired').mean() * 100)
gender_selection

Gender
Female               1.428571
Male                 4.800000
Non-Binary           2.678571
Prefer Not to Say    2.439024
Name: StageReached, dtype: float64

In [11]:
gender_rates = df.groupby('Gender')['StageReached'].apply(lambda x: (x == 'Hired').mean())
gender_air = gender_rates / gender_rates.max()
gender_air

Gender
Female               0.297619
Male                 1.000000
Non-Binary           0.558036
Prefer Not to Say    0.508130
Name: StageReached, dtype: float64

In [12]:
ethnicity_selection = df.groupby('Ethnicity')['StageReached'].apply(lambda x: (x == 'Hired').mean() * 100)
ethnicity_selection

Ethnicity
Asian              4.347826
Black              4.210526
Hispanic/Latinx    3.296703
Mixed              4.347826
Other              0.000000
White              0.000000
Name: StageReached, dtype: float64

In [13]:
ethnicity_rates = df.groupby('Ethnicity')['StageReached'].apply(lambda x: (x == 'Hired').mean())
ethnicity_air = ethnicity_rates / ethnicity_rates.max()
ethnicity_air

Ethnicity
Asian              1.000000
Black              0.968421
Hispanic/Latinx    0.758242
Mixed              1.000000
Other              0.000000
White              0.000000
Name: StageReached, dtype: float64

In [14]:
disability_selection = df.groupby('DisabilityStatus')['StageReached'].apply(lambda x: (x == 'Hired').mean() * 100)
disability_selection

DisabilityStatus
Cognitive        0.000000
Mental Health    8.000000
Other            0.000000
Physical         3.225806
Sensory          0.000000
Name: StageReached, dtype: float64

In [15]:
disability_rates = df.groupby('DisabilityStatus')['StageReached'].apply(lambda x: (x == 'Hired').mean())
disability_air = disability_rates / disability_rates.max()
disability_air

DisabilityStatus
Cognitive        0.000000
Mental Health    1.000000
Other            0.000000
Physical         0.403226
Sensory          0.000000
Name: StageReached, dtype: float64

In [16]:
role_selection = df.groupby('RoleType')['StageReached'].apply(lambda x: (x == 'Hired').mean() * 100)
role_selection

RoleType
Junior       3.821656
Mid-Level    3.488372
Senior       1.169591
Name: StageReached, dtype: float64

In [17]:
stage_counts_table = df['StageReached'].value_counts().reset_index()
stage_counts_table.columns = ['StageReached', 'Count']
stage_counts_table

  StageReached  Count
0      Applied    207
1     Screened    172
2  Interviewed     61
3  Shortlisted     46
4        Hired     14

In [18]:
stage_order = ['Applied', 'Screened', 'Interviewed', 'Shortlisted', 'Hired']

stage_counts = df['StageReached'].value_counts().reindex(stage_order)
dropoff_table = stage_counts.pct_change().abs() * 100
dropoff_table = dropoff_table.reset_index()
dropoff_table.columns = ['StageReached', 'DropoffPercent']
dropoff_table

  StageReached  DropoffPercent
0      Applied             NaN
1     Screened       16.908213
2  Interviewed       64.534884
3  Shortlisted       24.590164
4        Hired       69.565217

In [19]:
conversion_table = (stage_counts / stage_counts.shift(1) * 100).reset_index()
conversion_table.columns = ['StageReached', 'ConversionPercent']
conversion_table

  StageReached  ConversionPercent
0      Applied                NaN
1     Screened          83.091787
2  Interviewed          35.465116
3  Shortlisted          75.409836
4        Hired          30.434783

In [20]:
fairness_summary = {
    'Gender_AIR': gender_air,
    'Ethnicity_AIR': ethnicity_air,
    'Disability_AIR': disability_air
}

fairness_df = pd.concat(fairness_summary, axis=1)
fairness_df

                   Gender_AIR  Ethnicity_AIR  Disability_AIR
Female               0.297619            NaN             NaN
Male                 1.000000            NaN             NaN
Non-Binary           0.558036            NaN             NaN
Prefer Not to Say    0.508130            NaN             NaN
Asian                     NaN       1.000000             NaN
Black                     NaN       0.968421             NaN
Hispanic/Latinx           NaN       0.758242             NaN
Mixed                     NaN       1.000000             NaN
Other                     NaN       0.000000        0.000000
White                     NaN       0.000000             NaN
Cognitive                 NaN            NaN        0.000000
Mental Health             NaN            NaN        1.000000
Physical                  NaN            NaN        0.403226
Sensory                   NaN            NaN        0.000000

In [21]:
hires_by_demo = df[df['StageReached'] == 'Hired'].groupby(
    ['Gender', 'Ethnicity', 'DisabilityStatus']
).size().reset_index(name='Hires')
hires_by_demo

       Gender        Ethnicity DisabilityStatus  Hires
0        Male            Asian    Mental Health      1
1        Male  Hispanic/Latinx    Mental Health      1
2  Non-Binary            Mixed         Physical      1

In [22]:
stage_counts_table.to_csv("stage_counts.csv", index=False)
dropoff_table.to_csv("dropoff.csv", index=False)
conversion_table.to_csv("conversion.csv", index=False)
fairness_df.to_csv("fairness_summary.csv")
hires_by_demo.to_csv("hires_by_demo.csv", index=False)